title: Steven McDonald # your name (or website title) here
logo: "/images/logo crop.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science | Machine Learning 
  <br><br>
  London, UK 
  <br><br>
  <a href="https://www.linkedin.com/in/steven-j-mcdonald">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
